CREATE TABLE T_STOCK_04 (
daima	varchar(8)		,
xifenxingye	varchar(20)		,
caibaoniandong	varchar(8)	DEFAULT 0	,
caiwugengxin	varchar(8)	DEFAULT 0	,
shangshiriqi	varchar(8)	DEFAULT 0	,
zonggubenyi	float(20,5)	DEFAULT 0	,
BAguyi	float(20,5)	DEFAULT 0	,
Hguyi	float(20,5)	DEFAULT 0	,
zongzichanyi	float(20,5)	DEFAULT 0	,
jingzichanyi	float(20,5)	DEFAULT 0	,
shaoshuguquanyi	float(20,5)	DEFAULT 0	,
zichanfuzhailv	float(20,5)	DEFAULT 0	,
liudongzichanyi	float(20,5)	DEFAULT 0	,
gudingzichanyi	float(20,5)	DEFAULT 0	,
wuxingzichanyi	float(20,5)	DEFAULT 0	,
liudongfuzhaiyi	float(20,5)	DEFAULT 0	,
cunhuoyi	float(20,5)	DEFAULT 0	,
yingshouzhangkuanyi	float(20,5)	DEFAULT 0	,
zibengongjijinyi	float(20,5)	DEFAULT 0	,
yingyeshouruyi	float(20,5)	DEFAULT 0	,
yingyechengbenyi	float(20,5)	DEFAULT 0	,
yingyelirunyi	float(20,5)	DEFAULT 0	,
touzishouyiyi	float(20,5)	DEFAULT 0	,
lirunzongdongyi	float(20,5)	DEFAULT 0	,
shuihoulirunyi	float(20,5)	DEFAULT 0	,
jinglirunyi	float(20,5)	DEFAULT 0	,
koufeijinglirunyi	float(20,5)	DEFAULT 0	,
weifenlirunyi	float(20,5)	DEFAULT 0	,
jingyingxianjinliuyi	float(20,5)	DEFAULT 0	,
zongxianjinliuyi	float(20,5)	DEFAULT 0	,
gudongrenshu	float(20,5)	DEFAULT 0	,
renjunchigu	float(20,5)	DEFAULT 0	,
renjunshizhi	float(20,5)	DEFAULT 0	,
liruntongbi	float(20,5)	DEFAULT 0	,
shourutongbi	float(20,5)	DEFAULT 0	,
shijinglv	float(20,5)	DEFAULT 0	,
shixianlv	float(20,5)	DEFAULT 0	,
shixiaolv	float(20,5)	DEFAULT 0	,
guxilv	float(20,5)	DEFAULT 0	,
meigushouyi	float(20,5)	DEFAULT 0	,
meigujingzi	float(20,5)	DEFAULT 0	,
diaozhenghoujingzi	float(20,5)	DEFAULT 0	,
meigugongji	float(20,5)	DEFAULT 0	,
meiguweifenpei	float(20,5)	DEFAULT 0	,
meiguxianjinliu	float(20,5)	DEFAULT 0	,
quanyibi	float(20,5)	DEFAULT 0	,
jingyilv	float(20,5)	DEFAULT 0	,
maolilv	float(20,5)	DEFAULT 0	,
yingyelirunlv	float(20,5)	DEFAULT 0	,
jinglirunlv	float(20,5)	DEFAULT 0	,
yanfafeiyongyi	float(20,5)	DEFAULT 0	,
yuangongrenshu	float(20,5)	DEFAULT 0	,
PRIMARY KEY ( daima,caibaoniandong,caiwugengxin)
 )character set utf8;